name: CI/CD for NestJS Backend

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Verificar el código en el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Ejecutar pruebas
    #   - name: Run tests
    #     run: npm run test

      # Construir la aplicación
      - name: Build application
        run: npm run build

      # Subir el artefacto del build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: dist/

  deploy-dev:
    environment: DEVELOPMENT
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      # Descargar el artefacto del build
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: app-build

      # Configurar Azure CLI
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #   client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        #   auth-type: federatedCredential
     
      - name: 'Run Azure CLI commands 6'
        run: |
            az account show
            az group list
    
    #   - name: Retrieve secrets from Key Vault
    #     run: |
    #       # Comando para obtener secretos del Key Vault
    #       SECRET_VALUE=$(az keyvault secret show \
    #         --name CONTAINER-REGISTRY-DEV \
    #         --vault-name ${{ secrets.AZURE_KEYVAULT_NAME }} \
    #         --query value \
    #         -o tsv)
    #       echo "::add-mask::$SECRET_VALUE"
    #       echo "REGISTRY_SECRET=$SECRET_VALUE" >> $GITHUB_ENV
    
    #   - name: Use retrieved secrets
    #     run: |
    #       echo "Using secrets from Azure Key Vault"
    #       echo "API Key: $CONTAINER-REGISTRY-DEV"

      - name: Get secrets from Key Vault
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.AZURE_KEYVAULT_NAME }}
          secrets: |
            CONTAINER-REGISTRY-DEV

      # Use the secrets
      - name: Use secrets
        run: |
          echo "Using retrieved secrets"
          echo "SECRET_API_KEY: $CONTAINER-REGISTRY-DEV"

      
    #   # Desplegar en App Service
    #   - name: Deploy to Azure App Service
    #     uses: azure/webapps-deploy@v2
    #     with:
    #       app-name: <nombre-de-tu-app-service>
    #       slot-name: production
    #       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #       package: ./dist/
