name: CI/CD for NestJS Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Verificar el código en el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Ejecutar pruebas
    #   - name: Run tests
    #     run: npm run test

      # Construir la aplicación
      - name: Build application
        run: npm run build

      # Subir el artefacto del build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      # Descargar el artefacto del build
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: app-build

      # Configurar Azure CLI
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #   client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        #   auth-type: federatedCredential
     
      - name: Verify Azure Authentication
        run: |
          echo "Listing Azure resources 2..."
          az account show

    #   # Desplegar en App Service
    #   - name: Deploy to Azure App Service
    #     uses: azure/webapps-deploy@v2
    #     with:
    #       app-name: <nombre-de-tu-app-service>
    #       slot-name: production
    #       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
    #       package: ./dist/
